//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet.Demo.WebserviceTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEqptRoomService")]
    public interface IEqptRoomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEqptRoomService/deliveryCabinetList", ReplyAction="http://tempuri.org/IEqptRoomService/deliveryCabinetListResponse")]
        string deliveryCabinetList(string deliveryCabinetListObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEqptRoomService/deliverySystemUpdate", ReplyAction="http://tempuri.org/IEqptRoomService/deliverySystemUpdateResponse")]
        string deliverySystemUpdate(string deliverySystemUpdateObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEqptRoomServiceChannel : Cabinet.Demo.WebserviceTest.ServiceReference1.IEqptRoomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EqptRoomServiceClient : System.ServiceModel.ClientBase<Cabinet.Demo.WebserviceTest.ServiceReference1.IEqptRoomService>, Cabinet.Demo.WebserviceTest.ServiceReference1.IEqptRoomService {
        
        public EqptRoomServiceClient() {
        }
        
        public EqptRoomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EqptRoomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EqptRoomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EqptRoomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string deliveryCabinetList(string deliveryCabinetListObject) {
            return base.Channel.deliveryCabinetList(deliveryCabinetListObject);
        }
        
        public string deliverySystemUpdate(string deliverySystemUpdateObject) {
            return base.Channel.deliverySystemUpdate(deliverySystemUpdateObject);
        }
    }
}
